### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by cscully-allison** [hdc-arizona/roundtrip#9]
## Documentation Needs

Implement the following documentation:

- [x] Simple Example Notebooks With Multiple Visualizations
- [ ] Autodoc Generation of docstrings Under User Facing API calls 

### Visualization Developer
- [x] Installation Instructions
- [x] Prose form descriptions of with code snippets:
  - [x] Core Interaction with Software
  - [x] Data Assumptions
  - [x] Data Model for 1 Way "Pass by Value" 
  - [x] Data Model for 2 Way "Pass by Reference"
- [ ] Draw IO figures of Data Model and Abstract workings of RoundTrip
- [x] Best Practices
- [x] WebPack Guidance

### Notebook User
- [x] Clear explanation of ? operator

**Comment by cscully-allison** [comment]
I am hitting on a lot of these points with a tutorial in the wiki. I will address more theoretical concepts in the future.
